services:
  patient-service-db:
    image: postgres:18
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: patient-service-db
    ports:
      - "5000:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d patient-service-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  billing-service:
    build:
      context: .
      dockerfile: billing-service/Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal
    restart: unless-stopped

  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: "9001"
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient-service-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    networks:
      - internal
    depends_on:
      patient-service-db:
        condition: service_healthy
      billing-service:
        condition: service_started
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  patient-db-data: